In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('Malware dataset.csv')
dataset2 = dataset.copy()
dataset2 = dataset.drop(['classification'], axis=1)

X = dataset2.iloc[:,1:].values
y = dataset.iloc[:, 2].values

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
print(X_train)

[[  606 12288     0 ...    10     0     0]
 [  228 28672     0 ...     0     0     0]
 [  382  4096     0 ...     1     0     0]
 ...
 [  613 12288     0 ...    11     0     0]
 [  567  4096     0 ...     2     0     0]
 [  268     0     0 ...     0     0     0]]


In [9]:
print(y_train)

[0 1 0 ... 0 0 1]


In [10]:
print(X_test)

[[    582       0       0 ...       8       0       0]
 [    498       0       0 ...       0       0       0]
 [    227 1028096       0 ...       4       0       0]
 ...
 [    585    4096       0 ...       0       0       0]
 [    519       0       0 ...       7       0       0]
 [    831       0       0 ...       0       0       0]]


In [11]:
print(y_test)

[1 0 0 ... 1 0 0]


In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[ 0.36731703 -0.15969785  0.         ...  2.5559669   0.
   0.        ]
 [-0.941068   -0.14179605  0.         ... -0.50896701  0.
   0.        ]
 [-0.40802225 -0.16864875  0.         ... -0.20247362  0.
   0.        ]
 ...
 [ 0.39154638 -0.15969785  0.         ...  2.8624603   0.
   0.        ]
 [ 0.23232492 -0.16864875  0.         ...  0.10401977  0.
   0.        ]
 [-0.80261455 -0.1731242   0.         ... -0.50896701  0.
   0.        ]]


In [14]:
print(X_test)

[[ 0.28424496 -0.1731242   0.         ...  1.94298012  0.
   0.        ]
 [-0.00650727 -0.1731242   0.         ... -0.50896701  0.
   0.        ]
 [-0.94452933  0.95021383  0.         ...  0.71700655  0.
   0.        ]
 ...
 [ 0.29462897 -0.16864875  0.         ... -0.50896701  0.
   0.        ]
 [ 0.06618079 -0.1731242   0.         ...  1.63648673  0.
   0.        ]
 [ 1.14611763 -0.1731242   0.         ... -0.50896701  0.
   0.        ]]


In [15]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [16]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [0 0]]


In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[12528     0]
 [    1 12471]]


0.99996